### ISSUE TITLE
How is your version different from https://sourceforge.net/projects/libdxfrw/

### ISSUE THREAD

**Issue by rvt** [bert/libdxf#28]
See subject :)

**Comment by paolo-caroni** [comment]
Hello,
I just wrote some documentation and very little code so my answer may not be complete.
Bert will respond in a definitely more precise mode (and in a better english language).
libdxfrw is a very recent project, run by the community of LibreCAD.
libdxfrw also aims to read DWG files, libdxf not.
libdxfrw is written in C ++, libdxf is written in C.
Cheers

**Comment by rvt** [comment]
Paolo,

is a pure C interface important for this project?

**Comment by paolo-caroni** [comment]
I'm sorry,
You're asking the question to the wrong person.
It was Bert to writing the code and continues to do so.

I can say that rarely there are pieces of code not exactly pure C.
openhub describes them as C ++ (see https://www.openhub.net/p/libdxf/analyses/latest/languages_summary).

**Comment by bert** [comment]
Hi all,
I started a C library for C is one of the languages I know, besides pascal and some shell.
Pure C is not a goal in it self, see above.
For me C++ gets complicated and obfuscated very easily ... and overloading gets me disorientated ;-)
I (we?) could put some macros around headers to make libdxf useful in a C++ context, see the CONTRIBUTING file on coding style etc.
I hope this clarifies things a bit.
Kind regards,
Bert Timmerman.

**Comment by bert** [comment]
see line 228 ... 238 of CONTRIBUTING

**Comment by rvt** [comment]
Bert,

thanks for the clarifications. I was also wondering how we could combine forces with libdxfrw. There are a few dxf/dwg projects out there and if we work together we can create one 'better' (read more compatible) then different libs all with there own strength. let me know, I can introduce you to Rallaz (the main developer of libdxfrw) and we are using it in LibreCAD.

**Comment by bert** [comment]
Hi rvt,
I want libdxf to be as portable as possible ... I even try to avoid the glib badness (as much as possible).
The xmlto dependency for the documentation has to go away in the near future as I want to include only the generated documentation files in the distributed package (.deb, .rpm, etc.), and not bother the end users to have to install xmlto (though it is included in many distributions).
For developers and contributors this is different, if one wants to build from source I expect the (power) user to be able to choose between --enable-docs and --disable-docs during configuration time.
That said, I will include some C++ macros as described above in the near future, it on my todo list, though not reported as an issue yet ;-)
As far as contributing to libdxfrw: the goal of using parts of libdxf within LibreCAD is to narrow for me, I want to contribute to a wider audience and let as much people benefit from my efforts.
Although this will not prevent me from contributing any (L)GPL2+ project.
Kind regards,
Bert Timmerman.

**Comment by paolo-caroni** [comment]
Hello to all,
I would just point out that libdxfrw and libdxf have the same license (GPLv2+),
if the team of libdxfrw want can "stolen" lines of Bert's code (adding the copyright notice).
I would add also that my documentation (/doc/index.html) regards mainly changes in the DXF file in the various releases.
I wrote this documentation to help in my own way Lambert to write the code of lidxf, but can be used by all (FDLv1.3+).
I hope be useful,
cheers,
Paolo

**Comment by bert** [comment]
Hi all,
Before things get out of context or misunderstood:
I share my code with all for free, within the (L)GPL v2+ license framework and with FOSS mindset.
I just do not have the resources (time, energy, focus ...) to start actively contributing to a project in a language unfamiliar to me.
If there are any other questions or requests please open a new issue for them.
Kind regards,
Bert Timmerman.

**Comment by bert** [comment]
Hi all,

I added the compiler directives as in the example below, to all relevant header files, as to prevent C++ from mangling fuction and struct names.

#ifdef __cplusplus
extern "C" {
#endif

void foo (int i);

#ifdef __cplusplus
}
#endif

Kind regards,

Bert Timmerman.
